/*
* Interfaz grafica que representa la pantalla de inicio del juego, se pueden ingresar los nombres
* de los jugadores.
*/
package GUI;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class PantallaInicio extends javax.swing.JFrame {

    public PantallaInicio() {
        initComponents();
        this.setSize(565,300);
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        btnInicio = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblJugador1.setBackground(new java.awt.Color(0, 0, 0));
        lblJugador1.setFont(new java.awt.Font("Onyx", 0, 24)); // NOI18N
        lblJugador1.setText("Nombre del Jugador 1");
        getContentPane().add(lblJugador1);
        lblJugador1.setBounds(70, 110, 140, 27);

        lblJugador2.setFont(new java.awt.Font("Onyx", 0, 24)); // NOI18N
        lblJugador2.setText("Nombre del Jugador 2");
        getContentPane().add(lblJugador2);
        lblJugador2.setBounds(70, 170, 150, 20);
        getContentPane().add(txtJugador1);
        txtJugador1.setBounds(230, 110, 230, 30);
        getContentPane().add(txtJugador2);
        txtJugador2.setBounds(230, 170, 230, 30);

        btnInicio.setText("Iniciar Juego");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(230, 230, 230, 24);

        btnCerrar.setBackground(new java.awt.Color(153, 0, 0));
        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(510, 0, 50, 24);

        jLabel1.setFont(new java.awt.Font("Onyx", 0, 48)); // NOI18N
        jLabel1.setText("Juego de Ajedrez");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 220, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
     String Jugador1=txtJugador1.getText();
     String Jugador2=txtJugador2.getText();
     if(Jugador1.equals("")&&Jugador2.equals(""))
     {
         Jugador1="Jugador1";
         Jugador2="Jugador2";
     }
        VistaTablero ir = new VistaTablero(Jugador1,Jugador2);
       
          ir.setVisible(true);
          dispose();
   
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
   }
    ImageIcon inicio= new ImageIcon("Imagenes/inicio.png");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
